version: '3.8'

services:
  worker:
    build:
      context: ./worker
      target: development
    command: bin/server.sh
    volumes:
      - bundle:/bundle
      - ./worker:/opt/pinger:cached
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:rw
      - ~/.bash_history:/root/.bash_history
      - ~/.gitconfig:/root/.gitconfig:ro
    stdin_open: true
    tty: true
    env_file:
      - ./worker/.env.development
    tmpfs:
      - /tmp
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy


  redis:
    image: redis:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./worker/.env.development
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5


volumes:
  bundle:
